version: '{build}'
image: Visual Studio 2022
configuration: Release

before_build:
- cmd: dotnet restore

artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: LkrB3mJj6L7fC2wV42hy5HnBR8E247B4wJCH9Ge36mg4aZPii0j05ixmjtsR8s/x
  on:
    appveyor_repo_tag: true
